### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by mmoollllee** [fathonix/heimdall-osx-arm64#1]
Hey! I downloaded your release app and tried to run in different ways, but it won't work on macOs 13.4 (22F66) Intel Macbook Pro.
Finder tells me to delete the app as it's broken.

**Comment by fathonix** [comment]
Sorry, late answer.

Try to right-click the app, select Open then select Open again on the popup.

**Comment by mmoollllee** [comment]
Thanks for the not so late answer :)

I did that for both universal & x86_64 versions on a Intel Macbook Pro... Did not work..

BUT:

Running this
`xattr -cr heimdall-frontend.app`
gave me this error
`xattr: [Errno 13] Permission denied: 'heimdall-frontend.app/Contents/Frameworks/libusb-1.0.0.dylib'`
Running it again as sudo made the app work :)

So problem solved! Thank you for your work!!!
